---
  - name: install epel-release
    action: "{{ ansible_pkg_mgr }} name=epel-release state=latest"
  - name: install nginx web server
    action: "{{ ansible_pkg_mgr }} name=nginx state=present"
  - name: write nginx.conf
    action: template src=templates/nginx.conf.j2 dest=/etc/nginx/nginx.conf
    notify:
       - start nginx web server
